# This build script is used to compile a runnable jar on sourcehut
image: fedora/latest
environment:
    LC_ALL: en_US.utf8
packages:
  - java-latest-openjdk-devel
  - git-lfs
sources:
  - https://git.sr.ht/~nsg/osprey
tasks:
  - gradlew-assemble: |
      cd osprey
      ./gradlew -b simple.build.gradle assembleDist
artifacts:
    - osprey/build/distributions/osprey-3.1-BETA.tar
